---
- name: Install packages
  hosts: devin-mbp
  
  tasks:
  - name: Copy bashrc
    ansible.builtin.copy:
      src: bashrc
      dest: "~/.bashrc"
      owner: devin
      group: staff
      mode: '0640'
