---
- name: Install packages
  hosts: devin-mbp
  
  tasks:
  - name: Copy bashrc
    ansible.builtin.copy:
      src: tmux.conf
      dest: "~/.tmux.conf"
      owner: devin
      group: staff
      mode: '0640'
